[package]
name = "sneu_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19.3"
pulldown-cmark = "0.9.2"
gloo-utils = "0.1.5"
