name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Add wasm32-unknown-unknown
      run: rustup target add wasm32-unknown-unknown
    - name: Tauri
      run: cargo install --locked trunk && cargo install wasm-bindgen-cli
    - name: Build
      run: trunk build --release
    - name: Run tests
      run: cargo test --verbose
